#!/usr/bin/env python3
"""
Quick helper to show ELO system commands
"""

print("=== ELO RATING SYSTEM COMMANDS (UPDATED WITH TIERED STARTING RATINGS) ===")
print()
print("New Tiered Starting ELO System:")
print("  • Top 10 international teams (India, Australia, etc.): 1500 ELO")
print("  • Teams 11-20 (Ireland, Zimbabwe, etc.): 1400 ELO")
print("  • Other international teams (Uganda, Spain, etc.): 1300 ELO")
print("  • All league teams (IPL, BBL, etc.): 1500 ELO")
print()
print("Available commands:")
print()
print("1. Test the new tiered system:")
print("   python test_tiered_elo.py")
print()
print("2. Recalculate with new tiered ratings (TEST FIRST):")
print("   python setup_elo_system.py --recalculate --dry-run")
print()
print("3. Recalculate with new tiered ratings (ACTUAL):")
print("   python setup_elo_system.py --recalculate")
print()
print("4. Debug specific teams:")
print("   python debug_elo.py --find-uganda")
print("   python debug_elo.py --track-top")
print()
print("5. Verify existing data:")
print("   python setup_elo_system.py --verify-only")
print()
print("RECOMMENDED SEQUENCE:")
print("→ python test_tiered_elo.py                            # Verify tiered system")
print("→ python setup_elo_system.py --recalculate --dry-run  # Test recalculation")
print("→ python setup_elo_system.py --recalculate            # Apply new ratings")
